### ISSUE TITLE
Can't install plugin for release 1.7.0 

### ISSUE THREAD

**Issue by H1L021** [opendistro-for-elasticsearch/sql-kibana-plugin#69]
Kibana : 7.6.1
Elasticsearch SQL plugin : 1.7.0

Error Message :
Plugin installation was unsuccessful due to error "No kibana plugins found in archive" 

There is no link to download the kibana plugin for SQL but i downloaded the one here released 2 days ago but i couldn't install.

Help please

**Comment by chloe-zh** [comment]
Hi @H1L021 could you try this: https://github.com/opendistro-for-elasticsearch/sql-kibana-plugin/suites/680359166/artifacts/6271671

**Comment by H1L021** [comment]
didn't work 
```
root@elk-master:/usr/share/kibana# bin/kibana-plugin install --allow-root file:///home/username/sql-kibana.zip
Attempting to transfer from file:///home/username/sql-kibana.zip
Transferring 56861430 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"
```
